
ALTER DATABASE [databaseName]
SET QUERY_STORE = ON (
    OPERATION_MODE = READ_WRITE
    ,QUERY_CAPTURE_MODE = ALL
    -- ,MAX_PLANS_PER_QUERY = 200
    ,MAX_STORAGE_SIZE_MB = 5000
    ,CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30)
); 


